name: Java CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -buildfile build.xml
    - name: Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/jar/*.jar
